name: DDNS-GO
version: "v6.17.6"
slug: ddns_go
description: Automatically update public IPv4 or IPv6 addresses in DNS records
image: ghcr.io/orangeboychen/ha-addons-ddns-go
url: https://github.com/orangeboyChen/ha-addons
startup: application
boot: auto
init: false
arch:
  - amd64
  - aarch64
apparmor: true
ingress: true
ingress_port: 9876
panel_icon: mdi:dns
panel_title: DDNS-GO
options:
  pwd: ""
  frequency: 300
schema:
  pwd: str
  frequency: "int(10,)"
breaking_versions:
  - "6.6.9"
